config/routes.rb
Rails.application.routes.draw do
  root 'candidates#index'

  resources :candidates do
    collection do
      post :invite
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :email, uniqueness: true

  def self.access_spreadsheets
    session = GoogleDrive::Session.from_config("credentials.json")
    ws = session.spreadsheet_by_key("1xkofJa5iI3AQE4yWEoHqMTQ1QQ-VDsfUDDwV96QQDVM").worksheets[0]
  end

  def invite!
    data = attributes.except("id", "timestamp", "created_at", "updated_at")
    data["user_phone_number"] = data.delete "mobile"
    Talkpush::Candidate.invite(data)
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/concerns/talkpush.rb
module Talkpush
  extend ActiveSupport::Concern

  class Candidate
    def self.invite(data)
      url = "https://my.talkpush.com/api/talkpush_services/campaigns/3929/campaign_invitations"

      begin
        response = RestClient.post url, {
          # I didnt inclunde it on the ENV file I know this is not a good practice :D
          api_key: '48530ba23eef6b45ffbc95d7c20a60b9', 
          campaign_invitation: data
        }
        return true
      rescue response => error
        puts "error! #{error.inspect}"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all.order('created_at DESC')
  end

  def invite
    sheets = Candidate.access_spreadsheets

    if sheets.num_rows > 1
      last_row = sheets.rows.last
      candidate = Candidate.create(timestamp: last_row[0], first_name: last_row[1], last_name: last_row[2], email: last_row[3], mobile: last_row[4])
      if candidate.errors.any?
        redirect_to candidates_path, flash: { error: 'Candidate was already invited' }
      else
        candidate.invite!
        redirect_to candidates_path, flash: { success: 'Candidate was successfully invited' }
      end
    else
      redirect_to candidates_path, flash: { error: 'No new candidates found!' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-primary'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/index.html.erb
<div class="row">
  <%= link_to 'Sync Candidate', invite_candidates_path, class: 'btn btn-success', method: :post %>
  <table class=" table table-striped" data-sort-name="name" data-sort-order="desc">
    <thead>
    <tr>
    <th data-field="name" data-sortable="true">Name</th>
    <th data-field="email" data-sortable="true">Email</th>
    <th data-field="email" data-sortable="true">Mobile</th>
    </tr>
    </thead>

    <tbody>
      <% @candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.name %></td>
          <td><%= candidate.email %></td>
          <td><%= candidate.mobile %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CandidateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <% if flash.present? %>
      <% flash.each do |type, content| %>
        <%= render 'shared/flash_messages', type: type, content: content %>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" data-aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <div class="text">
    <%= content %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Rails Candidates</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>